// Node 22+ load client. Example: node tools/bots.mjs ws://localhost:8080/ws -n 100 --duration 600
import {setTimeout as sleep}from'node:timers/promises';
const url=process.argv[2]??'ws://localhost:8080/ws',args=process.argv.slice(3),arg=(name,fallback)=>{const i=args.indexOf(name);return i<0?fallback:Number(args[i+1])},N=arg('-n',100),duration=arg('--duration',60);let bytesIn=0,bytesOut=0,snapshots=0,rejects=0,disconnects=0,rttTotal=0,rttCount=0;
const half=v=>v*.5*Math.PI/180,wrap=v=>Math.atan2(Math.sin(v),Math.cos(v));
class Bot{constructor(i){this.i=i;this.id=0;this.tick=0;this.input=0;this.shot=0;this.ready=false;this.everReady=false;this.yaw=Math.random()*Math.PI*2;this.start=null;this.maxMove=0;this.pingAt=0;this.states=new Map;this.ws=new WebSocket(url);this.ws.binaryType='arraybuffer';this.ws.onopen=()=>this.send(this.join());this.ws.onmessage=e=>this.message(Buffer.from(e.data));this.ws.onclose=()=>{if(this.ready)disconnects++}}
 join(){const name=Buffer.from(`load-${this.i}`),fp=Buffer.from(`load_${this.i}_${Date.now()}`);return Buffer.concat([Buffer.from([1,10,name.length]),name,Buffer.from([3,0,0,0,0]),fp])}
 send(b){if(this.ws.readyState===WebSocket.OPEN){bytesOut+=b.length;this.ws.send(b)}}
 message(d){bytesIn+=d.length;const op=d[0];if(op===0x81){this.id=d.readUInt16LE(2);this.ready=this.everReady=true;return}if(op===0x82){this.snapshot(d);return}if(op===0x84&&this.pingAt){rttTotal+=Date.now()-this.pingAt;rttCount++;return}if(op===0x88){rejects++}}
 snapshot(d){this.tick=d.readUInt32LE(1);snapshots++;let o=8;for(let i=0,n=d[7];i<n;i++){const id=d.readUInt16LE(o),mask=d.readUInt16LE(o+2);o+=4;let s=this.states.get(id);if(mask===0x8000){s={x:d.readInt16LE(o)/100,y:d.readInt16LE(o+2)/100,z:d.readInt16LE(o+4)/100,yaw:half(d.readInt16LE(o+6)),pitch:half(d.readInt16LE(o+8)),vx:d.readInt8(o+10)/10,vz:d.readInt8(o+11)/10,hp:d[o+12],armor:d[o+13],state:d[o+14],weapon:d[o+15],shot:d[o+16],skin:d[o+17],weaponSkin:d[o+18],ultimate:d[o+19]};o+=20}else{if(!s)throw new Error(`missing baseline ${id}`);s={...s};if(mask&1){s.x+=d.readInt8(o++)/100;s.y+=d.readInt8(o++)/100;s.z+=d.readInt8(o++)/100}else if(mask&2){s.x=d.readInt16LE(o)/100;s.y=d.readInt16LE(o+2)/100;s.z=d.readInt16LE(o+4)/100;o+=6}if(mask&4){s.yaw=wrap(s.yaw+half(d.readInt8(o++)));s.pitch+=half(d.readInt8(o++))}else if(mask&8){s.yaw=half(d.readInt16LE(o));s.pitch=half(d.readInt16LE(o+2));o+=4}if(mask&16){s.vx=d.readInt8(o++)/10;s.vz=d.readInt8(o++)/10}if(mask&32){s.hp=d[o++];s.armor=d[o++]}if(mask&64)s.state=d[o++];if(mask&128)s.weapon=d[o++];if(mask&256)s.shot=d[o++];if(mask&512)s.skin=d[o++];if(mask&1024)s.weaponSkin=d[o++];if(mask&2048)s.ultimate=d[o++]}this.states.set(id,s);if(id===this.id){this.start??={x:s.x,z:s.z};this.maxMove=Math.max(this.maxMove,Math.hypot(s.x-this.start.x,s.z-this.start.z))}}}
 inputMsg(){const b=Buffer.alloc(12);b[0]=2;b.writeUInt16LE(this.input++&65535,1);if(this.input%120===0)this.yaw=Math.random()*Math.PI*2;b[3]=1;b.writeFloatLE(this.yaw,4);b.writeFloatLE(0,8);return b}
 fire(){const b=Buffer.alloc(16);b[0]=3;b.writeUInt16LE(++this.shot&65535,1);b.writeUInt32LE(this.tick,3);b[7]=0;b.writeFloatLE(Math.random()*Math.PI*2,8);b.writeFloatLE((Math.random()-.5)*.2,12);this.send(b)}
 ping(){this.pingAt=Date.now();this.send(Buffer.from([0xf0]))}close(){this.ready=false;this.ws.close()}}
console.log(`spawning ${N} clients for ${duration}s`);const bots=[];for(let i=0;i<N;i++){bots.push(new Bot(i));if(i%20===19)await sleep(100)}await sleep(1500);const inputTimer=setInterval(()=>{for(const b of bots)if(b.ready){b.send(b.inputMsg());if(Math.random()<.025)b.fire()}},17),pingTimer=setInterval(()=>bots.forEach(b=>b.ready&&b.ping()),2000),logTimer=setInterval(async()=>{let server={};try{server=await(await fetch(url.replace(/^ws/,'http').replace(/\/ws$/,'/api/stats'))).json()}catch{}console.log(JSON.stringify({joined:bots.filter(b=>b.ready).length,mbIn:+(bytesIn/1e6).toFixed(1),mbOut:+(bytesOut/1e6).toFixed(1),serverBps:server.outboundBps,tickP99:server.tickP99Ms,rssMB:Math.round(process.memoryUsage().rss/1e6)}))},5000);await sleep(duration*1000);clearInterval(inputTimer);clearInterval(pingTimer);clearInterval(logTimer);bots.forEach(b=>b.close());await sleep(250);const summary={requested:N,joined:bots.filter(b=>b.everReady).length,rejects,disconnects,seconds:duration,moved:bots.filter(b=>b.maxMove>.5).length,maxMove:+Math.max(0,...bots.map(b=>b.maxMove)).toFixed(2),mbIn:+(bytesIn/1e6).toFixed(2),mbOut:+(bytesOut/1e6).toFixed(2),snapshots,avgRttMs:rttCount?+(rttTotal/rttCount).toFixed(1):0,rssMB:Math.round(process.memoryUsage().rss/1e6)};console.log(JSON.stringify(summary,null,2));process.exit(summary.joined===N&&summary.moved===N&&rejects===0&&disconnects===0?0:1);
